CREATE TABLE student(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45),
age INTEGER,
country VARCHAR(45)
);
CREATE TABLE class(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45)
);
CREATE TABLE teacher(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45),
age INTEGER,
country VARCHAR(125)
);

